server:
  port: 3001

spring:
  application:
    name: manager-service

#  datasource:
#    druid:
#      #url: jdbc:mysql://localhost:3306/power-shop?useSSL=false&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
#      url: jdbc:mysql://192.168.230.128:3306/shop?useSSL=false&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
#      username: root
#      password: root
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      max-active: 30
#      min-idle: 3
#      initial-size: 3
#      validation-query: select 1
#      max-wait: 5000
#      stat-view-servlet:
#        enabled: true
#        login-username: admin
#        login-password: admin
#        allow:
#        deny:
#        url-pattern:
#          - /druid/*
#mybatis-plus:
#  mapper-locations: classpath:mapper/**/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#  jackson:
#    time-zone: GMT+8
#    date-format: yyyy-MM-dd HH:mm:ss
#  mvc:
#    format:
#      date-time: yyyy-MM-dd HH:mm:ss
#      date: yyyy-MM-dd
#      time: HH:mm:ss

